name: Create Advent of Code 2025 badges 

on: 
  push:
    paths:
      - '2025/src/**' # Triggers when changing solutions
  workflow_dispatch:

jobs:
  add_stars_2025:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joblo2213/aoc-badges-action@master
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION_SECRET }}
          year: 2025
          file: '2025/README.md'
      - uses: joblo2213/aoc-badges-action@master
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION_SECRET }}
          year: 2025
          file: 'README.md'
          starsRegex: '(?<=2025\]\(https:\/\/img\.shields\.io\/badge\/stars%20â­-)[0-9]+(?=-yellow)' 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: '**/README.md README.md'

